apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: node-exporter-smartd
spec:
  template:
    metadata:
      labels:
        app: 'smartd'
      annotations:
    spec:
      hostNetwork: True
      nodeSelector:
      containers:
      - name: smartd
        image: kfox1111/node-exporter-smartd:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /srv/txt_collector
            name: srv
        securityContext:
          privileged: true
      volumes:
        - name: srv
          hostPath:
            path: /var/lib/node-exporter
