apiVersion: v1
kind: Service
metadata:
  name: {{template "fullname" .}}
  labels:
    component: {{template "fullname" .}}
spec:
  type: {{ .Values.service.type }}
  selector:
    component: {{template "fullname" .}}
  ports:
  - name: http
    port: {{ .Values.service.httpPort }}
    targetPort: 5601
    protocol: TCP
  sessionAffinity: {{ .Values.service.sessionAffinity }}
