---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{template "fullname" .}}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{template "fullname" .}}-config
data:
  log4j2.properties: |-
    status = error
    name = LogstashPropertiesConfig

    appender.console.type = Console
    appender.console.name = plain_console
    appender.console.layout.type = PatternLayout
    appender.console.layout.pattern = [%d{ISO8601}][%-5p][%-25c] %m%n

    appender.json_console.type = Console
    appender.json_console.name = json_console
    appender.json_console.layout.type = JSONLayout
    appender.json_console.layout.compact = true
    appender.json_console.layout.eventEol = true

    rootLogger.level = ${sys:ls.log.level}
    rootLogger.appenderRef.console.ref = ${sys:ls.log.format}_console

  logstash.yml: |-
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
    xpack.monitoring.elasticsearch.url: {{ .Values.elasticsearch.url }}
    xpack.monitoring.elasticsearch.username: {{ .Values.elasticsearch.username }}
    xpack.monitoring.elasticsearch.password: {{ .Values.elasticsearch.password }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{template "fullname" .}}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{template "fullname" .}}-pipeline
data:
{{ toYaml .Values.pipelineFiles | indent 2 }}
