apiVersion: v1
kind: Service
metadata:
  name: {{template "fullname" .}}
  labels:
    component: {{template "fullname" .}}
spec:
  type: {{ .Values.service.type }}
  selector:
    component: {{template "fullname" .}}
  ports:
  - name: beats
    port: {{ .Values.service.beatsPort }}
    targetPort: 5044
    protocol: TCP
  - name: monitor
    port: {{ .Values.service.monitorPort }}
    targetPort: 9600
    protocol: TCP
