apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "fullname" . }}
data:
  heketi.json: |-
    {
        "_port_comment": "Heketi Server Port Number",
        "port" : "8080",

        "_use_auth": "Enable JWT authorization. Please enable for deployment",
        "use_auth" : false,

        "_jwt" : "Private keys for access",
        "jwt" : {
          "_admin" : "Admin has access to all APIs",
          "admin" : {
            "key" : "My Secret"
          },
          "_user" : "User only has access to /volumes endpoint",
          "user" : {
            "key" : "My Secret"
          }
        },

        "_backup_db_to_kube_secret": "Backup the heketi database to a Kubernetes secret when running in Kubernetes. Default is off.",
        "backup_db_to_kube_secret": true,

        "_glusterfs_comment": "GlusterFS Configuration",
        "glusterfs" : {

          "_executor_comment": "Execute plugin. Possible choices: mock, ssh",
          "executor" : "mock",

          "_db_comment": "Database file name",
          "db" : "/var/lib/heketi/heketi.db"
        }
      }
