---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{template "fullname" .}}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{template "fullname" .}}
data:
{{ toYaml .Values.configFiles | indent 2 }}
