apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: slow
provisioner: gluster.org/glusterfs-simple
parameters:
  brickrootPaths: >
    192.168.1.124:/var/lib/heketi/dev04,
    192.168.1.125:/var/lib/heketi/dev06,
    192.168.1.124:/var/lib/heketi/dev05,
    192.168.1.125:/var/lib/heketi/dev07
  volumeType: "replica 2"
