---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: gluster1
 annotations:
   volume.beta.kubernetes.io/storage-class: slow
spec:
 accessModes:
  - ReadWriteMany
 resources:
   requests:
     storage: 2Gi
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: gluster-web
spec:
  replicas: 2
  selector:
    role: web-frontend
  template:
    metadata:
      labels:
        role: web-frontend
    spec:
      containers:
      - name: web
        image: nginx
        ports:
          - name: web
            containerPort: 80
        volumeMounts:
            # name must match the volume name below
            - name: gluster
              mountPath: "/usr/share/nginx/html"
      volumes:
      - name: gluster
        persistentVolumeClaim:
          claimName: gluster1
---
kind: Service
apiVersion: v1
metadata:
  name: gluster-web
spec:
  ports:
    - port: 80
  selector:
    role: web-frontend
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: gluster-busybox
spec:
  replicas: 2
  selector:
    name: gluster-busybox
  template:
    metadata:
      labels:
        name: gluster-busybox
    spec:
      containers:
      - image: busybox
        command:
          - sh
          - -c
          - 'while true; do date > /mnt/index.html; hostname >> /mnt/index.html; sleep $(($RANDOM % 5 + 5)); done'
        imagePullPolicy: IfNotPresent
        name: busybox
        volumeMounts:
          # name must match the volume name below
          - name: gluster
            mountPath: "/mnt"
      volumes:
      - name: gluster
        persistentVolumeClaim:
          claimName: gluster1
