#!/usr/bin/env bash
set -eu
export LC_ALL=C

cat <<EOF
#cloud-config
---
hostname: ${NODE_HOSTNAME}

# Set SSH Key
ssh_authorized_keys:
- ${NODE_PUBLIC_KEY}

network:
  version: 2
  ethernets:
    mng:
      match:
        name: ${NODE_NET_DEVICE}*
      addresses:
        - ${NODE_ADDRESS}/${NODE_NETWORK_RANGE}
      gateway4: ${NODE_GATEWAY}
      nameservers:
        addresses: [${NODE_DNS}]

runcmd:
  - [ sh, -c, "echo '127.0.1.1  ${NODE_HOSTNAME}' >> /etc/hosts"]
EOF
